"""T421: E3 admissibility adapter (GU-adjacent physics <-> TaF capability boundary).

EXPLORATORY, RECORDED-TIER. No claim promotion. GU/pseudo-Hermitian QM is the
OBJECT OF STUDY and a two-sided structural check ONLY -- never cited as support
for a TaF statement. This module is IMPORT-FREE in the strong sense demanded by
the frozen D3 spec: the two functors below are built independently, and NEITHER
consumes the other's output.

Design (per greenlit D3 plan):

  One source category  Obs : a fixed finite Krein ambient (V, K) + a chosen
                             observable menu M (a unital *-subalgebra generated
                             by a finite generator set). Morphisms = menu
                             enlargement inclusions M subset M'.

  One target category  Adm : an admissibility structure (grading, verdict,
                             witness). verdict in {DECLARED = E0, FORCED = E3}.
                             Morphisms = verdict-monotone refinements
                             (FORCED -> DECLARED only; the taxonomy one-way rule).

  TWO functors of that ONE signature, built independently:

    F_TaF : M |-> (invariant decomposition of V ; rho = DECLARED iff some
            admissible operation generated by M recovers the separating datum d,
            else FORCED). Uses ONLY the menu algebra acting on two given lines.
            ZERO metric / ghost-parity / Mostafazadeh input.

    F_phys: M |-> (Mostafazadeh metric eta_M and its positive sector ; rho =
            DECLARED iff the menu pins a UNIQUE definite metric so no grading
            survives, else FORCED under the surviving superselection). Uses ONLY
            pseudo-Hermitian metric selection. ZERO TaF / recovery input.

  The adapter IS the natural transformation eta : F_TaF => F_phys, components
  isomorphisms in Adm, naturality squares commuting over enlargement arrows.

The SINGLE shared knob (identical predicate on both readings):
  Is the ghost-parity selector P central in the observable algebra?
    central  (reducible M, nontrivial commutant) => superselection survives => FORCED
    non-central (irreducible M, Schur commutant = C*I) => Mostafazadeh pins a
                DEFINITE metric => no grading => DECLARED.

Honest ceiling: a STRUCTURAL / kinematic natural iso on the E0/E3 fragment. The
dynamical lift ([P_ghost, S] = 0, the missing source action) is NOT built here
and stays gated. Global natural iso is predeclared OPEN with a falsifier (K1).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable, Protocol, runtime_checkable

import numpy as np

TOL = 1e-9

# ---------------------------------------------------------------------------
# Krein ambient (the shared object of study; GU adjacency = the numbers only)
# ---------------------------------------------------------------------------

I2 = np.eye(2, dtype=complex)
K_FORM = np.array([[0, 1], [1, 0]], dtype=complex)          # indefinite Krein form
P_PARITY = np.array([[0, 1], [1, 0]], dtype=complex)        # ghost-parity selector (= K here)
Z_GRADE = np.array([[1, 0], [0, -1]], dtype=complex)        # grading-breaking generator
# Null basis u = e1, v = e2 :  <u,v>_K = 1, <u,u>_K = <v,v>_K = 0
U_NULL = np.array([1, 0], dtype=complex)
V_NULL = np.array([0, 1], dtype=complex)
# P eigenlines: (u+v) K-norm +2 (physical, P-even); (u-v) K-norm -2 (ghost, P-odd)
LINE_PHYS = np.array([1, 1], dtype=complex)                 # separating datum: target line
LINE_GHOST = np.array([1, -1], dtype=complex)               # separating datum: source line
# Grading-preserving unitary (diag(2,3) in the P-eigenbasis) = 2.5 I - 0.5 P
U_PRESERVE = 2.5 * I2 - 0.5 * P_PARITY


def dagger(m: np.ndarray) -> np.ndarray:
    return m.conj().T


def k_norm(x: np.ndarray, k: np.ndarray = K_FORM) -> complex:
    return complex((dagger(x.reshape(-1, 1)) @ k @ x.reshape(-1, 1))[0, 0])


# ---------------------------------------------------------------------------
# Operator-algebra utilities (domain-neutral linear algebra)
# ---------------------------------------------------------------------------

def generated_algebra_basis(gens, n: int):
    """Linear basis of the unital *-algebra generated by ``gens`` (n x n)."""
    seed = [np.eye(n, dtype=complex)]
    for g in gens:
        seed.append(np.array(g, dtype=complex))
        seed.append(dagger(np.array(g, dtype=complex)))

    basis_vecs: list[np.ndarray] = []

    def add(mat: np.ndarray) -> bool:
        v = mat.reshape(-1)
        if basis_vecs:
            a = np.array(basis_vecs).T
            coef, *_ = np.linalg.lstsq(a, v, rcond=None)
            if np.linalg.norm(a @ coef - v) < TOL:
                return False
        basis_vecs.append(v)
        return True

    for m in seed:
        add(m)

    changed = True
    while changed:
        changed = False
        current = [bv.reshape(n, n) for bv in basis_vecs]
        for a_mat in current:
            for b_mat in seed:
                if add(a_mat @ b_mat):
                    changed = True
    return [bv.reshape(n, n) for bv in basis_vecs]


def commutant_dimension(gens, n: int) -> int:
    """dim { X : [g, X] = 0 for all generators g }."""
    rows = []
    for g in gens:
        g = np.array(g, dtype=complex)
        rows.append(np.kron(np.eye(n), g) - np.kron(g.T, np.eye(n)))
    a = np.vstack(rows)
    rank = np.linalg.matrix_rank(a, tol=TOL)
    return n * n - rank


def is_central(op: np.ndarray, gens, n: int) -> bool:
    """op is central in <gens>: op in the algebra AND commutes with every generator."""
    op = np.array(op, dtype=complex)
    for g in gens:
        g = np.array(g, dtype=complex)
        if np.linalg.norm(op @ g - g @ op) > TOL:
            return False
    basis = generated_algebra_basis(gens, n)
    a = np.array([b.reshape(-1) for b in basis]).T
    coef, *_ = np.linalg.lstsq(a, op.reshape(-1), rcond=None)
    return np.linalg.norm(a @ coef - op.reshape(-1)) < TOL


def _hermitian_basis(n: int):
    basis = []
    for i in range(n):
        e = np.zeros((n, n), dtype=complex)
        e[i, i] = 1.0
        basis.append(e)
    for i in range(n):
        for j in range(i + 1, n):
            e = np.zeros((n, n), dtype=complex)
            e[i, j] = 1.0
            e[j, i] = 1.0
            basis.append(e)
            e2 = np.zeros((n, n), dtype=complex)
            e2[i, j] = 1.0j
            e2[j, i] = -1.0j
            basis.append(e2)
    return basis


def metric_space(gens, n: int):
    """Hermitian solutions of Mostafazadeh's pseudo-Hermiticity intertwiner
    eta * g = g^dagger * eta for every generator g.

    Returns (dim, basis_metrics). This is metric SELECTION: an irreducible
    family pins dim == 1 (definite, unique up to scale); a reducible family
    leaves dim > 1 (a family that contains indefinite eta -> grading survives).
    """
    hbasis = _hermitian_basis(n)
    rows = []
    for g in gens:
        g = np.array(g, dtype=complex)
        gd = dagger(g)
        for h in hbasis:
            resid = h @ g - gd @ h  # linear in the coefficient of h
            rows.append(resid)
    # Build real constraint matrix over coefficients x (eta = sum x_k h_k).
    cmat = []
    for g in gens:
        g = np.array(g, dtype=complex)
        gd = dagger(g)
        blocks = [(h @ g - gd @ h).reshape(-1) for h in hbasis]
        m = np.array(blocks).T  # (n*n) x len(hbasis), complex
        cmat.append(np.vstack([m.real, m.imag]))
    c = np.vstack(cmat)
    # Null space of c (real).
    _, s, vh = np.linalg.svd(c)
    rank = int(np.sum(s > TOL))
    null = vh[rank:]
    metrics = []
    for row in null:
        eta = sum(coef * h for coef, h in zip(row, hbasis))
        metrics.append(eta)
    return len(metrics), metrics


def metric_is_uniquely_definite(gens, n: int):
    """(unique_definite, has_indefinite): does metric selection pin a single
    definite metric up to scale, and does the admissible family contain an
    indefinite metric (a surviving grading)?"""
    dim, metrics = metric_space(gens, n)
    if dim == 0:
        return False, False
    if dim == 1:
        eig = np.linalg.eigvalsh(metrics[0])
        definite = np.all(eig > TOL) or np.all(eig < -TOL)
        indefinite = (np.any(eig > TOL) and np.any(eig < -TOL))
        return bool(definite), bool(indefinite)
    # dim > 1 : sample the family for an indefinite representative.
    has_indef = False
    rng = np.random.default_rng(0)
    for _ in range(200):
        coefs = rng.normal(size=dim)
        eta = sum(c * m for c, m in zip(coefs, metrics))
        eig = np.linalg.eigvalsh(eta)
        if np.any(eig > TOL) and np.any(eig < -TOL):
            has_indef = True
            break
    return False, has_indef  # dim>1 => never uniquely definite


def recovery_exists(algebra_basis, line_from, line_to, n: int) -> bool:
    """Does the algebra contain m with m*line_from a nonzero vector on line_to?
    Equivalent: line_to in the subspace (algebra . line_from). Pure operational
    recoverability -- no metric, no grading, no ghost-parity semantics used."""
    v = line_from.reshape(n, 1)
    cols = [(a @ v).reshape(-1) for a in algebra_basis]
    w = np.array(cols).T
    target = line_to.reshape(-1)
    sol, *_ = np.linalg.lstsq(w, target, rcond=None)
    return np.linalg.norm(w @ sol - target) < TOL


# ---------------------------------------------------------------------------
# Categories Obs and Adm (the ONE shared signature)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ObsObject:
    """Object of Obs: fixed Krein ambient + a chosen observable menu M."""

    name: str
    n: int
    menu: tuple                      # generators of the *-algebra M (= <M_R>)
    line_from: np.ndarray            # separating datum d : source line (ghost)
    line_to: np.ndarray              # separating datum d : target line (physical)
    parity: np.ndarray               # ghost-parity selector P (ambient datum)

    def algebra_basis(self):
        return generated_algebra_basis(self.menu, self.n)


@dataclass(frozen=True)
class ObsMorphism:
    """Menu-enlargement inclusion M(source) subset M(target)."""

    name: str
    source: ObsObject
    target: ObsObject


@dataclass(frozen=True)
class AdmObject:
    """Object of Adm: an admissibility structure."""

    grading: str                     # "graded" | "ungraded"
    verdict: str                     # "FORCED" (E3) | "DECLARED" (E0)
    witness: dict = field(default_factory=dict)


VERDICT_RANK = {"FORCED": 0, "DECLARED": 1}  # enlarging only ever un-forces


@dataclass(frozen=True)
class AdmMorphism:
    """Verdict-monotone refinement: FORCED -> DECLARED allowed, reverse forbidden."""

    source: AdmObject
    target: AdmObject

    @property
    def monotone(self) -> bool:
        return VERDICT_RANK[self.target.verdict] >= VERDICT_RANK[self.source.verdict]


@runtime_checkable
class VerdictFunctor(Protocol):
    """The ONE signature both functors instantiate: Obs -> Adm."""

    def on_object(self, obj: ObsObject) -> AdmObject: ...

    def on_morphism(self, mor: ObsMorphism) -> AdmMorphism: ...


# ---------------------------------------------------------------------------
# F_TaF -- operational-recoverability functor (ZERO physics input)
# ---------------------------------------------------------------------------

class FTaF:
    """menu |-> (invariant decomposition ; DECLARED iff datum recoverable).

    Consumes ONLY: the menu algebra and the two given lines. Never references
    K_FORM, the metric, ghost-parity SEMANTICS, or Mostafazadeh. (The parity
    matrix, if present in a menu, is treated as a bare operator generating an
    algebra -- its Krein meaning is never used here.)
    """

    reads_physics = False

    def on_object(self, obj: ObsObject) -> AdmObject:
        basis = obj.algebra_basis()
        recoverable = recovery_exists(basis, obj.line_from, obj.line_to, obj.n)
        reducible = commutant_dimension(obj.menu, obj.n) > 1
        verdict = "DECLARED" if recoverable else "FORCED"
        grading = "graded" if reducible else "ungraded"
        return AdmObject(
            grading=grading,
            verdict=verdict,
            witness={
                "reading": "TaF-operational",
                "datum_recoverable": bool(recoverable),
                "algebra_dim": len(basis),
                "invariant_decomposition": reducible,
            },
        )

    def on_morphism(self, mor: ObsMorphism) -> AdmMorphism:
        return AdmMorphism(self.on_object(mor.source), self.on_object(mor.target))


# ---------------------------------------------------------------------------
# F_phys -- Mostafazadeh metric-selection functor (ZERO TaF input)
# ---------------------------------------------------------------------------

class FPhys:
    """menu |-> (Krein grading ; DECLARED iff a unique definite metric is pinned).

    Consumes ONLY: metric selection (pseudo-Hermiticity intertwiners). Never
    references recoverability, the separating-datum lines, or any TaF verdict.
    """

    reads_taf = False

    def on_object(self, obj: ObsObject) -> AdmObject:
        dim, _ = metric_space(obj.menu, obj.n)
        unique_definite, has_indef = metric_is_uniquely_definite(obj.menu, obj.n)
        # Irreducible family pins a definite metric -> ghosts merged -> no grading.
        if unique_definite and not has_indef:
            verdict, grading = "DECLARED", "ungraded"
        else:
            verdict, grading = "FORCED", "graded"
        return AdmObject(
            grading=grading,
            verdict=verdict,
            witness={
                "reading": "physics-metric",
                "metric_space_dim": dim,
                "unique_definite_metric": bool(unique_definite),
                "indefinite_metric_survives": bool(has_indef),
            },
        )

    def on_morphism(self, mor: ObsMorphism) -> AdmMorphism:
        return AdmMorphism(self.on_object(mor.source), self.on_object(mor.target))


# ---------------------------------------------------------------------------
# The adapter: natural transformation eta : F_TaF => F_phys
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EtaComponent:
    """eta_M : F_TaF(M) -> F_phys(M).  An Adm-iso iff both agree on (grading,
    verdict); the witness correspondence recoverable <=> definite-metric is the
    load-bearing content (K5 guard: content in the witness, not the bare verdict)."""

    taf: AdmObject
    phys: AdmObject

    @property
    def is_iso(self) -> bool:
        return self.taf.grading == self.phys.grading and self.taf.verdict == self.phys.verdict


def eta_component(obj: ObsObject) -> EtaComponent:
    return EtaComponent(FTaF().on_object(obj), FPhys().on_object(obj))


def naturality_square_commutes(mor: ObsMorphism) -> bool:
    """Square over the enlargement arrow commutes: both functors send it to the
    SAME Adm morphism and the eta components at both ends are isos."""
    f_taf, f_phys = FTaF(), FPhys()
    src = eta_component(mor.source)
    tgt = eta_component(mor.target)
    if not (src.is_iso and tgt.is_iso):
        return False
    taf_mor = f_taf.on_morphism(mor)
    phys_mor = f_phys.on_morphism(mor)
    # eta components are identities on equal Adm objects, so commuting reduces to
    # the two legs being the same Adm morphism (same endpoints, same direction).
    same_ends = (
        taf_mor.source.verdict == phys_mor.source.verdict
        and taf_mor.target.verdict == phys_mor.target.verdict
        and taf_mor.source.grading == phys_mor.source.grading
        and taf_mor.target.grading == phys_mor.target.grading
    )
    return same_ends and taf_mor.monotone and phys_mor.monotone


# ---------------------------------------------------------------------------
# The worked toy: the E0/E3 fragment on C^2
# ---------------------------------------------------------------------------

def build_objects():
    """M0 (reducible <I,P>), M_all (irreducible <P,Z>), M1 (grading-preserving)."""
    m0 = ObsObject(
        name="M0 = <I, P>",
        n=2,
        menu=(I2, P_PARITY),
        line_from=LINE_GHOST,
        line_to=LINE_PHYS,
        parity=P_PARITY,
    )
    m_all = ObsObject(
        name="M_all = <P, Z> = M2(C)",
        n=2,
        menu=(P_PARITY, Z_GRADE),
        line_from=LINE_GHOST,
        line_to=LINE_PHYS,
        parity=P_PARITY,
    )
    m1 = ObsObject(
        name="M1 = <I, P, U> (grading-preserving U)",
        n=2,
        menu=(I2, P_PARITY, U_PRESERVE),
        line_from=LINE_GHOST,
        line_to=LINE_PHYS,
        parity=P_PARITY,
    )
    return m0, m_all, m1


def run_adapter():
    """Run the full adapter on the toy and return a structured result dict."""
    m0, m_all, m1 = build_objects()
    arrow = ObsMorphism("M0 subset M_all", m0, m_all)
    arrow_pre = ObsMorphism("M0 subset M1", m0, m1)

    f_taf, f_phys = FTaF(), FPhys()

    def snapshot(obj):
        a_taf = f_taf.on_object(obj)
        a_phys = f_phys.on_object(obj)
        return {
            "name": obj.name,
            "P_central": is_central(obj.parity, obj.menu, obj.n),
            "commutant_dim": commutant_dimension(obj.menu, obj.n),
            "metric_space_dim": metric_space(obj.menu, obj.n)[0],
            "F_TaF": (a_taf.grading, a_taf.verdict),
            "F_phys": (a_phys.grading, a_phys.verdict),
            "eta_iso": eta_component(obj).is_iso,
            "taf_witness": a_taf.witness,
            "phys_witness": a_phys.witness,
        }

    return {
        "objects": {
            "M0": snapshot(m0),
            "M_all": snapshot(m_all),
            "M1": snapshot(m1),
        },
        "naturality_M0_to_Mall": naturality_square_commutes(arrow),
        "naturality_M0_to_M1": naturality_square_commutes(arrow_pre),
        "both_functors_typecheck": (
            isinstance(f_taf, VerdictFunctor) and isinstance(f_phys, VerdictFunctor)
        ),
        "shared_knob": "centrality of ghost-parity selector P in the observable algebra",
    }


if __name__ == "__main__":  # pragma: no cover
    import json

    res = run_adapter()
    print(json.dumps(res, indent=2, default=str))
