"""T481: internal scale-structure admission gate.

This module turns T480's "external bookkeeping vs earned internal structure"
burden into an executable admission gate. It does not show that internal scale
structure has been earned. It admits only:

1. external scale-label bookkeeping over T24/T38/T480 anchors, and
2. a synthetic future review-target shape with a predeclared internal generator,
   comparison domain, controls, and relabel-invariance checks.

Clock, duration, temporal-arrow, record-finality, scale-genesis, physics, and
claim-promotion readings remain blocked.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from models.scale_label_operation_gate import run as run_t480


ARTIFACT_ID = "T481-internal-scale-structure-admission-gate-v0.1"
VERDICT = "INTERNAL_SCALE_STRUCTURE_GATE_BUILT_REVIEW_ONLY_NO_CLOCK_PROMOTION"


@dataclass(frozen=True)
class ScaleStructureCandidate:
    """One proposed packet after the T480 scale-label gate."""

    candidate_id: str
    role: str
    declared_status: str
    transported_structure: str
    transport_law: str
    scale_label_operation: str
    comparison_domain: str
    admitted_reading: str
    local_taf_anchor: str
    internal_generating_rule: str = ""
    positive_and_negative_controls_declared: bool = False
    relabel_invariance_check_declared: bool = False
    declares_external_bookkeeping: bool = False
    declares_earned_internal_structure: bool = False
    label_only_without_operation: bool = False
    posthoc_comparison_domain: bool = False
    uses_hidden_calendar_or_time_order: bool = False
    derives_duration_or_arrow_from_scale_structure: bool = False
    changes_record_finality_by_scale_structure: bool = False
    imports_rg_or_conformal_mechanism: bool = False
    claims_scale_genesis_or_physics: bool = False
    requests_claim_or_posture_promotion: bool = False


def scale_structure_candidates() -> tuple[ScaleStructureCandidate, ...]:
    """Return the finite T481 candidate catalogue."""

    return (
        ScaleStructureCandidate(
            candidate_id="external_scale_label_bookkeeping",
            role="positive_bookkeeping_control",
            declared_status="external_bookkeeping",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport with T480 scale-label operation",
            scale_label_operation=(
                "attach finite scale label sigma to each observer site and "
                "record the labeled transport edges available for comparison"
            ),
            comparison_domain=(
                "pairs of labeled observer sites joined by declared T38 "
                "transport edges"
            ),
            admitted_reading=(
                "external comparison bookkeeping only; no internal scale "
                "structure or clock earned"
            ),
            local_taf_anchor="T24/T38/T480",
            declares_external_bookkeeping=True,
        ),
        ScaleStructureCandidate(
            candidate_id="synthetic_internal_scale_review_target",
            role="positive_review_control",
            declared_status="internal_structure_review_target",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport with T480 scale-label operation",
            scale_label_operation=(
                "derive a finite scale relation from a predeclared internal "
                "compatibility operator on D1 field patches"
            ),
            comparison_domain=(
                "predeclared equivalence classes of D1 field patches and "
                "transport edges generated by the compatibility operator"
            ),
            admitted_reading=(
                "admitted only as a future review target; internal structure "
                "not earned by this gate"
            ),
            local_taf_anchor="T24/T38/T480",
            internal_generating_rule=(
                "finite compatibility operator over D1 field patches, named "
                "before packet construction"
            ),
            positive_and_negative_controls_declared=True,
            relabel_invariance_check_declared=True,
            declares_earned_internal_structure=True,
        ),
        ScaleStructureCandidate(
            candidate_id="internal_by_assertion",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="call the scale labels internal",
            comparison_domain="labeled sites",
            admitted_reading="internal structure follows from the word internal",
            local_taf_anchor="T24/T38 named but burden unpaid",
            declares_earned_internal_structure=True,
        ),
        ScaleStructureCandidate(
            candidate_id="label_restatement_as_structure",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="",
            comparison_domain="labels only",
            admitted_reading="scale words count as structure",
            local_taf_anchor="T24/T38 named but no operation",
            declares_earned_internal_structure=True,
            label_only_without_operation=True,
        ),
        ScaleStructureCandidate(
            candidate_id="posthoc_comparison_domain",
            role="hostile_control",
            declared_status="internal_structure_review_target",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="attach finite labels after seeing the data",
            comparison_domain="chosen after the separator is known",
            admitted_reading="comparison domain selected post hoc",
            local_taf_anchor="T24/T38 named but domain not predeclared",
            internal_generating_rule="posthoc selector",
            positive_and_negative_controls_declared=True,
            relabel_invariance_check_declared=True,
            declares_earned_internal_structure=True,
            posthoc_comparison_domain=True,
        ),
        ScaleStructureCandidate(
            candidate_id="hidden_calendar_internal_scale",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="assign scale labels from hidden calendar order",
            comparison_domain="calendar-ordered labels",
            admitted_reading="hidden time order becomes internal scale",
            local_taf_anchor="T24/T38 named but hidden time source",
            internal_generating_rule="calendar order",
            declares_earned_internal_structure=True,
            uses_hidden_calendar_or_time_order=True,
        ),
        ScaleStructureCandidate(
            candidate_id="duration_from_internal_order",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="order internal labels micro < meso < macro",
            comparison_domain="ordered scale labels",
            admitted_reading="ordered labels define duration and arrow",
            local_taf_anchor="T24/T38 named but clock overread",
            internal_generating_rule="ordered labels",
            declares_earned_internal_structure=True,
            derives_duration_or_arrow_from_scale_structure=True,
        ),
        ScaleStructureCandidate(
            candidate_id="record_finality_from_internal_scale",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="mark macro-scale fields as final",
            comparison_domain="macro-scale labeled sites",
            admitted_reading="internal scale changes finality status",
            local_taf_anchor="T24/T38 named but finality overread",
            internal_generating_rule="macro label",
            declares_earned_internal_structure=True,
            changes_record_finality_by_scale_structure=True,
        ),
        ScaleStructureCandidate(
            candidate_id="rg_fixed_point_internal_source",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="RG/conformal scale data",
            transport_law="external beta-function or conformal mechanism",
            scale_label_operation="identify conformal fixed point as internal scale",
            comparison_domain="RG scale classes",
            admitted_reading="external fixed point supplies TaF scale genesis",
            local_taf_anchor="external RG/conformal mechanism",
            internal_generating_rule="external fixed point",
            declares_earned_internal_structure=True,
            imports_rg_or_conformal_mechanism=True,
            claims_scale_genesis_or_physics=True,
        ),
        ScaleStructureCandidate(
            candidate_id="promotion_shortcut_packet",
            role="hostile_control",
            declared_status="internal_structure",
            transported_structure="T24 field-valued D1 profile",
            transport_law="T38 H1+ transport",
            scale_label_operation="declare internal scale structure",
            comparison_domain="labeled transport edges",
            admitted_reading="D1 and scale-genesis claim promotion are earned",
            local_taf_anchor="T24/T38/T480 promotion shortcut",
            internal_generating_rule="asserted internal scale",
            declares_earned_internal_structure=True,
            claims_scale_genesis_or_physics=True,
            requests_claim_or_posture_promotion=True,
        ),
    )


def run() -> dict[str, Any]:
    """Run the T481 internal scale-structure admission gate."""

    anchor_checks = _anchor_checks()
    evaluations = [
        _evaluate_candidate(candidate, anchor_checks)
        for candidate in scale_structure_candidates()
    ]
    admitted = [
        row["candidate_id"]
        for row in evaluations
        if row["admitted"]
    ]
    hostile_violations = [
        row["candidate_id"]
        for row in evaluations
        if row["role"] == "hostile_control" and row["admitted"]
    ]
    expected_admissions = [
        "external_scale_label_bookkeeping",
        "synthetic_internal_scale_review_target",
    ]
    gate_passed = (
        anchor_checks["t480_gate_passed"]
        and admitted == expected_admissions
        and not hostile_violations
    )

    return {
        "artifact_id": ARTIFACT_ID,
        "objective": (
            "Make T480's external-bookkeeping versus earned-internal-scale "
            "burden executable while blocking clocks, durations, finality "
            "changes, RG/conformal mechanism imports, physics claims, and "
            "promotion shortcuts."
        ),
        "local_anchor_checks": anchor_checks,
        "candidate_evaluations": evaluations,
        "admitted_candidate_ids": admitted,
        "hostile_violations": hostile_violations,
        "overall_verdict": {
            "verdict": VERDICT,
            "gate_passed": gate_passed,
            "external_bookkeeping_admitted": "external_scale_label_bookkeeping" in admitted,
            "synthetic_internal_review_target_admitted": (
                "synthetic_internal_scale_review_target" in admitted
            ),
            "hostile_controls_blocked": not hostile_violations,
            "claim_ledger_update": "none",
            "north_star_update": "none",
            "roadmap_update": "none",
            "public_posture_update": "none",
            "physics_claim_earned": False,
            "scale_genesis_theorem_earned": False,
            "record_clock_or_duration_earned": False,
            "internal_scale_structure_earned": False,
            "reading": (
                "T481 separates external scale bookkeeping from the minimum "
                "shape of a future internal-scale-structure review target. "
                "External labels are admitted only as comparison-domain "
                "bookkeeping over T24/T38/T480. A synthetic internal packet is "
                "admitted only as a review target when it predeclares an "
                "internal generator, comparison domain, controls, and relabel "
                "invariance. This gate earns no internal scale structure, "
                "clock, duration, finality change, scale-genesis theorem, "
                "physics support, claim movement, or public-posture movement."
            ),
        },
        "future_packet_minimum": [
            "state whether the scale label is external bookkeeping or claimed internal structure",
            "declare the transported structure and transport law separately from the scale label",
            "predeclare the comparison domain before selecting a witness or separator",
            "for internal-structure review, name an internal generating rule over TaF objects",
            "include positive and negative controls plus a relabel-invariance check",
            "block hidden calendar order, duration, temporal-arrow, finality, RG/conformal mechanism, physics, and promotion overreads",
        ],
        "not_earned": [
            "internal scale structure",
            "record clock",
            "duration or temporal arrow",
            "record-finality change",
            "scale-genesis theorem",
            "physics or conformal-gravity claim",
            "D1 promotion",
            "RG/TaF equivalence theorem",
            "claim-ledger movement",
            "roadmap movement",
            "North Star movement",
            "public-posture movement",
        ],
    }


def render_markdown(result: dict[str, Any]) -> str:
    """Render T481 results as Markdown."""

    verdict = result["overall_verdict"]
    anchor_rows = [
        f"| {key} | {value} |"
        for key, value in result["local_anchor_checks"].items()
    ]
    candidate_rows = []
    for row in result["candidate_evaluations"]:
        blockers = ", ".join(row["blockers"]) or "none"
        candidate_rows.append(
            "| {candidate_id} | {role} | {declared_status} | {decision} | {route_label} | {blockers} |".format(
                candidate_id=row["candidate_id"],
                role=row["role"],
                declared_status=row["declared_status"],
                decision=row["decision"],
                route_label=row["route_label"],
                blockers=blockers,
            )
        )
    minimum = [f"- {item}" for item in result["future_packet_minimum"]]
    not_earned = [f"- {item}" for item in result["not_earned"]]

    return "\n".join(
        [
            "# T481 - Internal Scale Structure Admission Gate - v0.1 results",
            "",
            "> Review gate only. No claim status, roadmap, README, North Star, "
            "public-posture, hard-policy, physics, scale-genesis, clock, "
            "duration, finality, or cross-repo movement.",
            "",
            "- Spec: `tests/T481-internal-scale-structure-admission-gate.md`",
            "- Model: `models/internal_scale_structure_admission_gate.py`",
            "- Tests: `tests/test_internal_scale_structure_admission_gate.py`",
            "- Artifact JSON: `results/T481-internal-scale-structure-admission-gate-v0.1.json`",
            "- Source open problem: `open-problems/rg-flow-as-multiscale-transport-analogy.md`",
            "- Local anchors: T24, T38, T479, and T480",
            "",
            f"## Overall verdict: {verdict['verdict']}",
            "",
            verdict["reading"],
            "",
            "## Local Anchor Checks",
            "",
            "| check | value |",
            "| --- | --- |",
            *anchor_rows,
            "",
            "## Candidate Evaluations",
            "",
            "| candidate | role | declared status | decision | route | blockers |",
            "| --- | --- | --- | --- | --- | --- |",
            *candidate_rows,
            "",
            "## Future Packet Minimum",
            "",
            *minimum,
            "",
            "## What This Does Not Earn",
            "",
            *not_earned,
            "",
        ]
    )


def _anchor_checks() -> dict[str, Any]:
    t480 = run_t480()
    t480_minimum = t480["future_packet_minimum"]
    return {
        "t480_gate_passed": t480["overall_verdict"]["gate_passed"],
        "t480_external_or_internal_status_required": (
            "state whether the label is external bookkeeping or earned internal structure"
            in t480_minimum
        ),
        "t480_comparison_edges_required": (
            "state what observers and transport edges can compare after labeling"
            in t480_minimum
        ),
        "t480_no_clock_or_duration_earned": (
            t480["overall_verdict"]["record_clock_or_duration_earned"] is False
        ),
        "t480_no_scale_genesis_earned": (
            t480["overall_verdict"]["scale_genesis_theorem_earned"] is False
        ),
        "t480_positive_packet_bookkeeping_only": (
            t480["admitted_candidate_ids"] == ["declared_scale_section_bookkeeping"]
        ),
    }


def _evaluate_candidate(
    candidate: ScaleStructureCandidate,
    anchor_checks: dict[str, Any],
) -> dict[str, Any]:
    blockers: list[str] = []

    if not anchor_checks["t480_gate_passed"]:
        blockers.append("t480_gate_missing")
    if not candidate.declared_status:
        blockers.append("external_or_internal_status_not_declared")
    if not candidate.transported_structure:
        blockers.append("transported_structure_not_named")
    if not candidate.transport_law:
        blockers.append("transport_law_not_named")
    if not candidate.scale_label_operation:
        blockers.append("scale_label_operation_not_declared")
    if not candidate.comparison_domain:
        blockers.append("comparison_domain_not_declared")
    if candidate.label_only_without_operation:
        blockers.append("label_word_without_operation")
    if candidate.posthoc_comparison_domain:
        blockers.append("comparison_domain_selected_posthoc")
    if candidate.uses_hidden_calendar_or_time_order:
        blockers.append("hidden_calendar_or_time_order")
    if candidate.derives_duration_or_arrow_from_scale_structure:
        blockers.append("duration_or_arrow_derived_from_scale_structure")
    if candidate.changes_record_finality_by_scale_structure:
        blockers.append("record_finality_changed_by_scale_structure")
    if candidate.imports_rg_or_conformal_mechanism:
        blockers.append("rg_or_conformal_mechanism_imported")
    if candidate.claims_scale_genesis_or_physics:
        blockers.append("scale_genesis_or_physics_claim_overread")
    if candidate.requests_claim_or_posture_promotion:
        blockers.append("claim_or_public_posture_promotion_shortcut")
    if candidate.local_taf_anchor.startswith("external"):
        blockers.append("no_local_taf_anchor")

    if candidate.declares_earned_internal_structure:
        if not candidate.internal_generating_rule:
            blockers.append("internal_generating_rule_not_declared")
        if not candidate.positive_and_negative_controls_declared:
            blockers.append("positive_negative_controls_missing")
        if not candidate.relabel_invariance_check_declared:
            blockers.append("relabel_invariance_check_missing")
    elif not candidate.declares_external_bookkeeping:
        blockers.append("packet_status_not_external_or_internal")

    external_admitted = (
        not blockers
        and candidate.declares_external_bookkeeping
        and candidate.role == "positive_bookkeeping_control"
    )
    internal_review_admitted = (
        not blockers
        and candidate.declares_earned_internal_structure
        and candidate.role == "positive_review_control"
    )
    admitted = external_admitted or internal_review_admitted

    if external_admitted:
        route_label = "EXTERNAL_SCALE_BOOKKEEPING_ADMITTED_NO_PROMOTION"
        decision = "admit_external_bookkeeping"
    elif internal_review_admitted:
        route_label = "INTERNAL_SCALE_REVIEW_TARGET_ADMITTED_NO_PROMOTION"
        decision = "admit_synthetic_review_target"
    else:
        route_label = "SCALE_STRUCTURE_PACKET_BLOCKED"
        decision = "reject_or_block"

    return {
        "candidate_id": candidate.candidate_id,
        "role": candidate.role,
        "declared_status": candidate.declared_status,
        "transported_structure": candidate.transported_structure,
        "transport_law": candidate.transport_law,
        "scale_label_operation": candidate.scale_label_operation,
        "comparison_domain": candidate.comparison_domain,
        "internal_generating_rule": candidate.internal_generating_rule,
        "admitted_reading": candidate.admitted_reading,
        "local_taf_anchor": candidate.local_taf_anchor,
        "admitted": admitted,
        "decision": decision,
        "route_label": route_label,
        "blockers": blockers,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-results", action="store_true")
    args = parser.parse_args()

    result = run()
    if args.write_results:
        results_dir = Path("results")
        results_dir.mkdir(exist_ok=True)
        json_path = results_dir / f"{ARTIFACT_ID}.json"
        md_path = results_dir / f"{ARTIFACT_ID}-results.md"
        json_path.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
        md_path.write_text(render_markdown(result), encoding="utf-8")
    else:
        print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
