"""T43: Local persistence accumulation mechanism audit.

T42 separated local persistence accumulation from reconciliation lag. T43 asks
what finite mechanisms can change local accumulation while propagation is held
fixed.

The mechanisms here are intentionally finite generators of local event deltas.
They are not physical clock models and do not derive proper time.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from models.local_persistence_reconciliation import (
    ComparisonEvent,
    ComparisonObservation,
    LocalPersistenceReconciliationSystem,
    RecordChannel,
    make_node,
    observe_comparison,
)


EVENT_COUNT = 10


@dataclass(frozen=True)
class MechanismTrace:
    """One generated local accumulation trace."""

    name: str
    mechanism_type: str
    parameters: dict[str, int | float | str]
    deltas: tuple[int, ...]
    total_accumulation: int
    mean_rate: float
    depends_on_propagation: bool


@dataclass(frozen=True)
class MechanismCase:
    """Comparison of two nodes generated by one candidate mechanism family."""

    name: str
    hypothesis_id: str
    source_trace: MechanismTrace
    target_trace: MechanismTrace
    propagation_delay_events: int
    observation: ComparisonObservation
    produces_local_difference: bool
    independent_of_propagation: bool
    preserves_t42_split: bool
    verdict: str
    interpretation: str


@dataclass(frozen=True)
class PropagationControl:
    """Control showing propagation changes lag without changing local accumulation."""

    name: str
    zero_delay_observation: ComparisonObservation
    delayed_observation: ComparisonObservation
    accumulation_difference_changed: bool
    reconciliation_lag_changed: bool
    verdict: str


@dataclass(frozen=True)
class PropagationShadowCounterexample:
    """A rejected candidate that makes accumulation depend on propagation."""

    name: str
    fixed_topology_observation: ComparisonObservation
    varied_topology_observation: ComparisonObservation
    fixed_topology_produces_difference: bool
    varied_topology_produces_difference: bool
    eliminated: bool
    reason: str


@dataclass(frozen=True)
class EquivalenceClass:
    """Mechanism traces with the same finite delta signature."""

    signature: tuple[int, ...]
    members: tuple[str, ...]
    observationally_equivalent: bool


@dataclass(frozen=True)
class HypothesisEvaluation:
    """T43 hypothesis verdict."""

    hypothesis_id: str
    claim: str
    status: str
    evidence_for: tuple[str, ...]
    evidence_against: tuple[str, ...]
    verdict: str


@dataclass(frozen=True)
class T43Result:
    """Full T43 analysis output."""

    mechanism_cases: tuple[MechanismCase, ...]
    propagation_control: PropagationControl
    propagation_shadow_counterexample: PropagationShadowCounterexample
    equivalence_classes: tuple[EquivalenceClass, ...]
    hypothesis_evaluations: tuple[HypothesisEvaluation, ...]
    best_supported_hypothesis: str
    minimal_extension: str
    theorem: str
    boundary: str
    recommendation: str


def intrinsic_stabilization_trace(
    name: str,
    rate: int,
    event_count: int = EVENT_COUNT,
) -> MechanismTrace:
    """Local accumulation set directly by a node-local rate parameter."""

    deltas = tuple(rate for _ in range(event_count))
    return MechanismTrace(
        name=name,
        mechanism_type="intrinsic_stabilization_rate",
        parameters={"rate": rate, "event_count": event_count},
        deltas=deltas,
        total_accumulation=sum(deltas),
        mean_rate=sum(deltas) / event_count,
        depends_on_propagation=False,
    )


def resource_budget_trace(
    name: str,
    update_demand: int,
    stabilization_budget: int,
    event_count: int = EVENT_COUNT,
) -> MechanismTrace:
    """Local accumulation limited by a finite per-step stabilization budget."""

    delta = min(update_demand, stabilization_budget)
    deltas = tuple(delta for _ in range(event_count))
    return MechanismTrace(
        name=name,
        mechanism_type="finite_resource_budget",
        parameters={
            "update_demand": update_demand,
            "stabilization_budget": stabilization_budget,
            "event_count": event_count,
        },
        deltas=deltas,
        total_accumulation=sum(deltas),
        mean_rate=sum(deltas) / event_count,
        depends_on_propagation=False,
    )


def interaction_density_trace(
    name: str,
    base_rate: int,
    coupling_strength: int,
    interaction_count: int,
    event_count: int = EVENT_COUNT,
) -> MechanismTrace:
    """Local accumulation generated by local interaction density."""

    delta = base_rate + coupling_strength * interaction_count
    deltas = tuple(delta for _ in range(event_count))
    return MechanismTrace(
        name=name,
        mechanism_type="interaction_density",
        parameters={
            "base_rate": base_rate,
            "coupling_strength": coupling_strength,
            "interaction_count": interaction_count,
            "event_count": event_count,
        },
        deltas=deltas,
        total_accumulation=sum(deltas),
        mean_rate=sum(deltas) / event_count,
        depends_on_propagation=False,
    )


def propagation_shadow_trace(
    name: str,
    base_rate: int,
    propagation_delay_events: int,
    delay_penalty: int,
    event_count: int = EVENT_COUNT,
) -> MechanismTrace:
    """Rejected candidate: local accumulation is reduced by propagation delay."""

    delta = max(0, base_rate - propagation_delay_events * delay_penalty)
    deltas = tuple(delta for _ in range(event_count))
    return MechanismTrace(
        name=name,
        mechanism_type="propagation_shadow",
        parameters={
            "base_rate": base_rate,
            "propagation_delay_events": propagation_delay_events,
            "delay_penalty": delay_penalty,
            "event_count": event_count,
        },
        deltas=deltas,
        total_accumulation=sum(deltas),
        mean_rate=sum(deltas) / event_count,
        depends_on_propagation=True,
    )


def _system_from_traces(
    name: str,
    source_trace: MechanismTrace,
    target_trace: MechanismTrace,
    propagation_delay_events: int,
) -> LocalPersistenceReconciliationSystem:
    source = make_node("source", source_trace.deltas, source_trace.name)
    target = make_node("target", target_trace.deltas, target_trace.name)
    return LocalPersistenceReconciliationSystem(
        name=name,
        description=f"T43 mechanism comparison: {name}",
        nodes=(source, target),
        channels=(
            RecordChannel(
                source_id="source",
                target_id="target",
                delay_events=propagation_delay_events,
                noise=0.0,
            ),
        ),
        comparisons=(
            ComparisonEvent(
                name=f"{name}_comparison",
                source_id="source",
                target_id="target",
                source_local_index=EVENT_COUNT,
                target_local_index=EVENT_COUNT,
            ),
        ),
    )


def _observe_traces(
    name: str,
    source_trace: MechanismTrace,
    target_trace: MechanismTrace,
    propagation_delay_events: int,
) -> ComparisonObservation:
    system = _system_from_traces(name, source_trace, target_trace, propagation_delay_events)
    return observe_comparison(system, system.comparisons[0])


def build_mechanism_case(
    name: str,
    hypothesis_id: str,
    source_trace: MechanismTrace,
    target_trace: MechanismTrace,
    propagation_delay_events: int,
    interpretation: str,
) -> MechanismCase:
    """Build and classify a fixed-topology mechanism comparison."""

    observation = _observe_traces(name, source_trace, target_trace, propagation_delay_events)
    produces_local_difference = observation.local_accumulation_difference != 0
    independent = (
        not source_trace.depends_on_propagation
        and not target_trace.depends_on_propagation
        and propagation_delay_events == 0
    )
    preserves_split = produces_local_difference and observation.reconciliation_lag_events == 0
    if produces_local_difference and independent:
        verdict = "supported"
    elif (
        produces_local_difference
        and not source_trace.depends_on_propagation
        and not target_trace.depends_on_propagation
        and propagation_delay_events > 0
    ):
        verdict = "combined_effects_witness"
    else:
        verdict = "not_supported"
    return MechanismCase(
        name=name,
        hypothesis_id=hypothesis_id,
        source_trace=source_trace,
        target_trace=target_trace,
        propagation_delay_events=propagation_delay_events,
        observation=observation,
        produces_local_difference=produces_local_difference,
        independent_of_propagation=independent,
        preserves_t42_split=preserves_split,
        verdict=verdict,
        interpretation=interpretation,
    )


def intrinsic_mechanism_case() -> MechanismCase:
    return build_mechanism_case(
        name="intrinsic_rate_difference",
        hypothesis_id="H1",
        source_trace=intrinsic_stabilization_trace("intrinsic_fast", rate=2),
        target_trace=intrinsic_stabilization_trace("intrinsic_slow", rate=1),
        propagation_delay_events=0,
        interpretation=(
            "Different node-local rates produce accumulation differences while "
            "the comparison channel has zero delay."
        ),
    )


def resource_budget_mechanism_case() -> MechanismCase:
    return build_mechanism_case(
        name="resource_budget_difference",
        hypothesis_id="H2",
        source_trace=resource_budget_trace(
            "resource_full_budget",
            update_demand=2,
            stabilization_budget=2,
        ),
        target_trace=resource_budget_trace(
            "resource_limited_budget",
            update_demand=2,
            stabilization_budget=1,
        ),
        propagation_delay_events=0,
        interpretation=(
            "A finite stabilization budget limits one node's local accumulation "
            "even though propagation is unchanged."
        ),
    )


def interaction_density_mechanism_case() -> MechanismCase:
    return build_mechanism_case(
        name="interaction_density_difference",
        hypothesis_id="H3",
        source_trace=interaction_density_trace(
            "dense_local_coupling",
            base_rate=1,
            coupling_strength=1,
            interaction_count=1,
        ),
        target_trace=interaction_density_trace(
            "sparse_local_coupling",
            base_rate=1,
            coupling_strength=1,
            interaction_count=0,
        ),
        propagation_delay_events=0,
        interpretation=(
            "Local interaction density changes the accumulation rate without "
            "changing reconciliation topology."
        ),
    )


def combined_effects_case() -> MechanismCase:
    return build_mechanism_case(
        name="resource_difference_with_delay",
        hypothesis_id="H2",
        source_trace=resource_budget_trace(
            "resource_full_budget_delayed",
            update_demand=2,
            stabilization_budget=2,
        ),
        target_trace=resource_budget_trace(
            "resource_limited_budget_delayed",
            update_demand=2,
            stabilization_budget=1,
        ),
        propagation_delay_events=3,
        interpretation=(
            "Local accumulation difference and reconciliation lag can coexist "
            "and remain separately measurable."
        ),
    )


def build_propagation_control() -> PropagationControl:
    """Fixed intrinsic accumulation, varied propagation."""

    source = intrinsic_stabilization_trace("same_intrinsic_source", rate=1)
    target = intrinsic_stabilization_trace("same_intrinsic_target", rate=1)
    zero_delay = _observe_traces("same_intrinsic_zero_delay", source, target, 0)
    delayed = _observe_traces("same_intrinsic_delayed", source, target, 4)
    accumulation_changed = (
        zero_delay.local_accumulation_difference != delayed.local_accumulation_difference
    )
    lag_changed = zero_delay.reconciliation_lag_events != delayed.reconciliation_lag_events
    return PropagationControl(
        name="fixed_intrinsic_vary_propagation",
        zero_delay_observation=zero_delay,
        delayed_observation=delayed,
        accumulation_difference_changed=accumulation_changed,
        reconciliation_lag_changed=lag_changed,
        verdict=(
            "pass: propagation changes reconciliation lag but not local accumulation"
            if lag_changed and not accumulation_changed
            else "fail"
        ),
    )


def build_propagation_shadow_counterexample() -> PropagationShadowCounterexample:
    """Show a candidate mechanism that collapses into propagation delay."""

    fixed_source = propagation_shadow_trace(
        "shadow_source_fixed",
        base_rate=2,
        propagation_delay_events=1,
        delay_penalty=1,
    )
    fixed_target = propagation_shadow_trace(
        "shadow_target_fixed",
        base_rate=2,
        propagation_delay_events=1,
        delay_penalty=1,
    )
    fixed_obs = _observe_traces("shadow_fixed_topology", fixed_source, fixed_target, 0)

    varied_source = propagation_shadow_trace(
        "shadow_source_no_delay",
        base_rate=2,
        propagation_delay_events=0,
        delay_penalty=1,
    )
    varied_target = propagation_shadow_trace(
        "shadow_target_delayed",
        base_rate=2,
        propagation_delay_events=1,
        delay_penalty=1,
    )
    varied_obs = _observe_traces("shadow_varied_topology", varied_source, varied_target, 0)

    fixed_diff = fixed_obs.local_accumulation_difference != 0
    varied_diff = varied_obs.local_accumulation_difference != 0
    eliminated = (not fixed_diff) and varied_diff
    return PropagationShadowCounterexample(
        name="propagation_shadow",
        fixed_topology_observation=fixed_obs,
        varied_topology_observation=varied_obs,
        fixed_topology_produces_difference=fixed_diff,
        varied_topology_produces_difference=varied_diff,
        eliminated=eliminated,
        reason=(
            "The candidate produces local accumulation differences only when "
            "propagation parameters differ. Under fixed topology it produces no "
            "difference, so it is delay in disguise."
        ),
    )


def search_equivalent_parameterizations() -> tuple[EquivalenceClass, ...]:
    """Find finite traces shared by different mechanism families."""

    traces = (
        intrinsic_stabilization_trace("intrinsic_rate_2", rate=2),
        resource_budget_trace("resource_demand_2_budget_2", update_demand=2, stabilization_budget=2),
        interaction_density_trace(
            "interaction_base_1_coupling_1_count_1",
            base_rate=1,
            coupling_strength=1,
            interaction_count=1,
        ),
        intrinsic_stabilization_trace("intrinsic_rate_1", rate=1),
        resource_budget_trace("resource_demand_2_budget_1", update_demand=2, stabilization_budget=1),
        interaction_density_trace(
            "interaction_base_1_coupling_1_count_0",
            base_rate=1,
            coupling_strength=1,
            interaction_count=0,
        ),
    )
    grouped: dict[tuple[int, ...], list[str]] = {}
    for trace in traces:
        grouped.setdefault(trace.deltas, []).append(trace.name)
    return tuple(
        EquivalenceClass(
            signature=signature,
            members=tuple(members),
            observationally_equivalent=len(members) > 1,
        )
        for signature, members in grouped.items()
        if len(members) > 1
    )


def evaluate_hypotheses(
    mechanism_cases: tuple[MechanismCase, ...],
    propagation_control: PropagationControl,
    shadow: PropagationShadowCounterexample,
    equivalence_classes: tuple[EquivalenceClass, ...],
) -> tuple[HypothesisEvaluation, ...]:
    """Evaluate H0-H5 from T43 evidence."""

    supported_ids = {case.hypothesis_id for case in mechanism_cases if case.verdict == "supported"}
    has_equivalence = any(eq.observationally_equivalent for eq in equivalence_classes)

    return (
        HypothesisEvaluation(
            hypothesis_id="H0",
            claim="No additional mechanism exists within the current finite framework.",
            status="rejected",
            evidence_for=(),
            evidence_against=(
                "Intrinsic rate, resource budget, and interaction density all produce local differences with zero delay.",
                "The propagation control shows delay changes lag without changing local accumulation.",
            ),
            verdict="Rejected within the finite model.",
        ),
        HypothesisEvaluation(
            hypothesis_id="H1",
            claim="Local accumulation depends only on intrinsic node-local update rules.",
            status="partially_supported",
            evidence_for=(
                "The intrinsic_rate_difference case produces local accumulation difference with fixed propagation.",
            ),
            evidence_against=(
                "Resource and interaction mechanisms produce the same observable effect without being only intrinsic-rate labels.",
            ),
            verdict="Supported as one mechanism, not as the unique mechanism.",
        ),
        HypothesisEvaluation(
            hypothesis_id="H2",
            claim="Local accumulation depends on finite local resources.",
            status="partially_supported",
            evidence_for=(
                "The resource_budget_difference case produces local accumulation difference with fixed propagation.",
                "Finite budget is a small extension: it changes event deltas without changing D1RestrictionSystem or TTN.",
            ),
            evidence_against=(
                "The same traces can be generated by intrinsic-rate and interaction-density parameterizations.",
            ),
            verdict="Promising as a mechanistic interpretation, but not uniquely identified by T43.",
        ),
        HypothesisEvaluation(
            hypothesis_id="H3",
            claim="Local accumulation depends on local interaction density or environmental coupling.",
            status="partially_supported",
            evidence_for=(
                "The interaction_density_difference case produces local accumulation difference with fixed propagation.",
            ),
            evidence_against=(
                "The trace is observationally equivalent to simpler intrinsic-rate and resource-budget traces.",
            ),
            verdict="Supported as one finite mechanism, not uniquely identified.",
        ),
        HypothesisEvaluation(
            hypothesis_id="H4",
            claim="Several mechanisms are mathematically equivalent under finite models.",
            status="best_supported" if has_equivalence else "not_supported",
            evidence_for=(
                "Intrinsic, resource, and interaction mechanisms can generate identical delta signatures.",
                "The finite observations cannot distinguish mechanisms that produce the same local trace.",
            ),
            evidence_against=(
                "Equivalence is trace-level only; richer observables could separate mechanisms later.",
            ),
            verdict=(
                "Best supported. T43 identifies a mechanism-equivalence class rather than one unique cause."
                if has_equivalence
                else "Not supported because no equivalence class was found."
            ),
        ),
        HypothesisEvaluation(
            hypothesis_id="H5",
            claim="A different mechanism emerges that better explains the observed separation.",
            status="not_earned",
            evidence_for=(
                "The propagation-shadow candidate usefully exposes a boundary case.",
            ),
            evidence_against=(
                "The boundary case is eliminated as disguised propagation, not promoted as a better mechanism.",
                f"Supported mechanism IDs were {tuple(sorted(supported_ids))}.",
            ),
            verdict="Not earned in T43.",
        ),
    )


def run_t43_analysis() -> T43Result:
    """Run the T43 mechanism audit."""

    mechanism_cases = (
        intrinsic_mechanism_case(),
        resource_budget_mechanism_case(),
        interaction_density_mechanism_case(),
        combined_effects_case(),
    )
    propagation_control = build_propagation_control()
    shadow = build_propagation_shadow_counterexample()
    equivalence_classes = search_equivalent_parameterizations()
    hypotheses = evaluate_hypotheses(
        mechanism_cases,
        propagation_control,
        shadow,
        equivalence_classes,
    )
    return T43Result(
        mechanism_cases=mechanism_cases,
        propagation_control=propagation_control,
        propagation_shadow_counterexample=shadow,
        equivalence_classes=equivalence_classes,
        hypothesis_evaluations=hypotheses,
        best_supported_hypothesis="H4",
        minimal_extension=(
            "Add a node-local accumulation generator as metadata around T42 "
            "local histories. Do not modify D1RestrictionSystem or "
            "TypedTransportNetwork."
        ),
        theorem=(
            "Finite Local Mechanism Equivalence Theorem: multiple finite "
            "node-local mechanisms can change local persistence accumulation "
            "with propagation held fixed, and distinct mechanism parameterizations "
            "can generate identical local delta traces."
        ),
        boundary=(
            "T43 compares finite trace generators only. It does not derive proper "
            "time, does not introduce spacetime dynamics, and does not identify a "
            "unique physical cause of local accumulation differences."
        ),
        recommendation=(
            "Promote the local accumulation generator as a minimal mathematical "
            "sidecar for future tests. Treat resource budget and interaction "
            "density as promising interpretations, but keep H4 as the current "
            "verdict because the finite traces are observationally equivalent."
        ),
    )


def t43_result_to_dict(result: T43Result) -> dict[str, Any]:
    """Serialize T43 result for JSON output."""

    return asdict(result)
