"""T2: dynamical quantum measurement record finality lab.

The model is a finite, standard-library-only measurement chain:

    system qubit -> apparatus pointer -> environment fragments

All dynamics are reversible CNOT interactions in the computational Z basis.
The lab computes:

* reduced system-apparatus pointer coherence after tracing the environment;
* classical Z-basis mutual information between the system and each record;
* Quantum-Darwinism-style environmental redundancy;
* observer-relative D1 profiles for different access windows.

This is not a collapse model and not a full decoherence simulation. It is the
smallest executable substrate test for whether T22's observable map survives
when records are generated by dynamics rather than declared as table entries.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from math import log2, sqrt


QUBITS = ("S", "A", "E1", "E2", "E3")
POINTER_BASIS = "computational_z"
INFORMATION_THRESHOLD_BITS = 0.9


@dataclass(frozen=True)
class Interaction:
    step: int
    name: str
    control: str
    target: str
    record_holder: str
    branch_root: str
    inverse_operation: str


@dataclass(frozen=True)
class ObserverWindow:
    name: str
    accessible_holders: frozenset[str]
    reconstruction_threshold: int


@dataclass(frozen=True)
class Record:
    holder: str
    qubit: str
    created_by: str
    branch_root: str
    inverse_operation: str


@dataclass(frozen=True)
class D1Profile:
    accessible_support: int
    holder_redundancy: int
    branch_support: int
    reversal_cost: int

    def as_tuple(self) -> tuple[int, int, int, int]:
        return (
            self.accessible_support,
            self.holder_redundancy,
            self.branch_support,
            self.reversal_cost,
        )


@dataclass(frozen=True)
class ObserverAnalysis:
    observer: ObserverWindow
    accessible_records: tuple[str, ...]
    d1_profile: D1Profile
    accessible_environment_r_delta: int
    interpretation: str


@dataclass(frozen=True)
class StageAnalysis:
    step: int
    name: str
    active_records: tuple[Record, ...]
    pointer_coherence_abs: float
    system_apparatus_probabilities: dict[str, float]
    fragment_information_bits: dict[str, float]
    environment_r_delta_total: int
    observers: tuple[ObserverAnalysis, ...]


@dataclass(frozen=True)
class MeasurementFinalityResult:
    qubits: tuple[str, ...]
    pointer_basis: str
    interactions: tuple[Interaction, ...]
    observers: tuple[ObserverWindow, ...]
    stages: tuple[StageAnalysis, ...]
    verdict: dict[str, bool]
    interpretation: dict[str, str]


def measurement_interactions() -> tuple[Interaction, ...]:
    return (
        Interaction(
            step=1,
            name="measurement_cnot_S_to_A",
            control="S",
            target="A",
            record_holder="apparatus",
            branch_root="z_pointer_measurement",
            inverse_operation="inverse_measurement_cnot_S_to_A",
        ),
        Interaction(
            step=2,
            name="decoherence_copy_A_to_E1",
            control="A",
            target="E1",
            record_holder="env_left",
            branch_root="z_pointer_measurement",
            inverse_operation="inverse_copy_A_to_E1",
        ),
        Interaction(
            step=3,
            name="decoherence_copy_A_to_E2",
            control="A",
            target="E2",
            record_holder="env_right",
            branch_root="z_pointer_measurement",
            inverse_operation="inverse_copy_A_to_E2",
        ),
        Interaction(
            step=4,
            name="decoherence_copy_A_to_E3",
            control="A",
            target="E3",
            record_holder="env_remote",
            branch_root="z_pointer_measurement",
            inverse_operation="inverse_copy_A_to_E3",
        ),
    )


def measurement_observers() -> tuple[ObserverWindow, ...]:
    return (
        ObserverWindow(
            "apparatus_observer",
            frozenset({"apparatus"}),
            reconstruction_threshold=1,
        ),
        ObserverWindow(
            "local_lab_observer",
            frozenset({"apparatus", "env_left"}),
            reconstruction_threshold=2,
        ),
        ObserverWindow(
            "remote_environment_observer",
            frozenset({"env_right", "env_remote"}),
            reconstruction_threshold=2,
        ),
        ObserverWindow(
            "outside_observer",
            frozenset(),
            reconstruction_threshold=1,
        ),
    )


def run_measurement_finality_lab() -> MeasurementFinalityResult:
    interactions = measurement_interactions()
    observers = measurement_observers()
    state = _initial_state()
    records: list[Record] = []
    stages: list[StageAnalysis] = []

    for interaction in interactions:
        state = _apply_cnot(
            state,
            _qubit_index(interaction.control),
            _qubit_index(interaction.target),
        )
        records.append(
            Record(
                holder=interaction.record_holder,
                qubit=interaction.target,
                created_by=interaction.name,
                branch_root=interaction.branch_root,
                inverse_operation=interaction.inverse_operation,
            )
        )
        stages.append(
            _analyze_stage(
                step=interaction.step,
                name=interaction.name,
                state=state,
                records=tuple(records),
                observers=observers,
            )
        )

    final_stage = stages[-1]
    local_lab = _observer_by_name(final_stage, "local_lab_observer")
    outside = _observer_by_name(final_stage, "outside_observer")
    remote = _observer_by_name(final_stage, "remote_environment_observer")
    return MeasurementFinalityResult(
        qubits=QUBITS,
        pointer_basis=POINTER_BASIS,
        interactions=interactions,
        observers=observers,
        stages=tuple(stages),
        verdict={
            "unitary_dynamics_only_no_collapse": True,
            "pointer_basis_explicit": POINTER_BASIS == "computational_z",
            "decoherence_occurs_after_environment_copy": (
                stages[0].pointer_coherence_abs > 0.0
                and stages[1].pointer_coherence_abs == 0.0
            ),
            "environment_redundancy_grows_dynamically": (
                [stage.environment_r_delta_total for stage in stages] == [0, 1, 2, 3]
            ),
            "d1_profiles_depend_on_observer_access": (
                local_lab.d1_profile.as_tuple() != outside.d1_profile.as_tuple()
                and remote.d1_profile.as_tuple() != outside.d1_profile.as_tuple()
            ),
            "decohered_but_inaccessible_case_detected": (
                final_stage.pointer_coherence_abs == 0.0
                and final_stage.environment_r_delta_total == 3
                and outside.d1_profile.accessible_support == 0
            ),
            "redundancy_exceeds_branch_support": (
                final_stage.environment_r_delta_total == 3
                and local_lab.d1_profile.branch_support == 1
            ),
            "q1_adds_observer_access_distinction": True,
        },
        interpretation={
            "main_result": (
                "The same unitary chain can be fully decohered in the pointer "
                "basis while an outside observer has D1 profile (0, 0, 0, 0). "
                "This is a concrete decohered-but-inaccessible case."
            ),
            "d1_vs_quantum_darwinism": (
                "Environmental R_delta grows from 0 to 3 as fragments are "
                "dynamically copied, but D1 remains observer-indexed and keeps "
                "branch support separate from raw redundancy."
            ),
            "guardrail": (
                "The model uses reversible unitary interactions and never "
                "selects a collapse outcome. It does not solve the measurement "
                "problem or derive Born probabilities."
            ),
            "interpretation_boundary": (
                "Under a unitary/no-collapse reading, the global state remains "
                "a coherent entangled state while observer-relative records are "
                "computed from reduced states and access windows. T2 uses this "
                "as a guardrail, not as an endorsement of an interpretation."
            ),
            "claim_recommendation": (
                "Keep Q1 partially supported. T2 v0.1 shows that D1 adds an "
                "observer-access distinction beyond decoherence/R_delta in this "
                "toy substrate, while branch support and reversal cost remain "
                "proxy-level quantities."
            ),
        },
    )


def run_t2_analysis() -> dict[str, object]:
    result = run_measurement_finality_lab()
    return {
        "qubits": list(result.qubits),
        "pointer_basis": result.pointer_basis,
        "information_threshold_bits": INFORMATION_THRESHOLD_BITS,
        "interactions": [asdict(interaction) for interaction in result.interactions],
        "observers": [
            {
                "name": observer.name,
                "accessible_holders": sorted(observer.accessible_holders),
                "reconstruction_threshold": observer.reconstruction_threshold,
            }
            for observer in result.observers
        ],
        "stages": [_stage_to_dict(stage) for stage in result.stages],
        "verdict": result.verdict,
        "interpretation": result.interpretation,
    }


def _analyze_stage(
    *,
    step: int,
    name: str,
    state: dict[int, complex],
    records: tuple[Record, ...],
    observers: tuple[ObserverWindow, ...],
) -> StageAnalysis:
    fragment_information = {
        qubit: _mutual_information_bits(state, "S", qubit)
        for qubit in QUBITS
        if qubit != "S"
    }
    environment_r_delta = sum(
        1
        for qubit in ("E1", "E2", "E3")
        if fragment_information[qubit] >= INFORMATION_THRESHOLD_BITS
    )
    return StageAnalysis(
        step=step,
        name=name,
        active_records=records,
        pointer_coherence_abs=round(_pointer_coherence_abs(state), 12),
        system_apparatus_probabilities=_system_apparatus_probabilities(state),
        fragment_information_bits={
            qubit: round(value, 12) for qubit, value in fragment_information.items()
        },
        environment_r_delta_total=environment_r_delta,
        observers=tuple(
            _analyze_observer(observer, records, fragment_information)
            for observer in observers
        ),
    )


def _analyze_observer(
    observer: ObserverWindow,
    records: tuple[Record, ...],
    fragment_information: dict[str, float],
) -> ObserverAnalysis:
    accessible_records = tuple(
        record
        for record in records
        if record.holder in observer.accessible_holders
        and fragment_information[record.qubit] >= INFORMATION_THRESHOLD_BITS
    )
    environment_r_delta = sum(
        1 for record in accessible_records if record.qubit.startswith("E")
    )
    support = len(accessible_records)
    profile = D1Profile(
        accessible_support=support,
        holder_redundancy=len({record.holder for record in accessible_records}),
        branch_support=len({record.branch_root for record in accessible_records}),
        reversal_cost=_reversal_cost_below_threshold(
            support, observer.reconstruction_threshold
        ),
    )
    return ObserverAnalysis(
        observer=observer,
        accessible_records=tuple(record.holder for record in accessible_records),
        d1_profile=profile,
        accessible_environment_r_delta=environment_r_delta,
        interpretation=_observer_interpretation(observer.name, profile),
    )


def _observer_interpretation(observer_name: str, profile: D1Profile) -> str:
    if profile.accessible_support == 0:
        return f"{observer_name} has no finalized accessible record in this window."
    if profile.accessible_support < 2:
        return f"{observer_name} has a local record but no redundant accessible witness."
    return f"{observer_name} has a redundant observer-relative record."


def _initial_state() -> dict[int, complex]:
    zero_index = 0
    system_one_index = 1 << (len(QUBITS) - 1 - _qubit_index("S"))
    amplitude = 1.0 / sqrt(2.0)
    return {zero_index: amplitude, system_one_index: amplitude}


def _apply_cnot(
    state: dict[int, complex], control_index: int, target_index: int
) -> dict[int, complex]:
    output: dict[int, complex] = {}
    target_mask = 1 << (len(QUBITS) - 1 - target_index)
    for basis_index, amplitude in state.items():
        if _bit_at(basis_index, control_index) == 1:
            basis_index ^= target_mask
        output[basis_index] = output.get(basis_index, 0j) + amplitude
    return output


def _pointer_coherence_abs(state: dict[int, complex]) -> float:
    reduced = _reduced_density_matrix(state, keep=("S", "A"))
    return abs(reduced.get((0b00, 0b11), 0j))


def _system_apparatus_probabilities(state: dict[int, complex]) -> dict[str, float]:
    probabilities = {"00": 0.0, "01": 0.0, "10": 0.0, "11": 0.0}
    for basis_index, amplitude in state.items():
        key = f"{_bit_at(basis_index, _qubit_index('S'))}{_bit_at(basis_index, _qubit_index('A'))}"
        probabilities[key] += abs(amplitude) ** 2
    return {key: round(value, 12) for key, value in probabilities.items()}


def _mutual_information_bits(
    state: dict[int, complex], left_qubit: str, right_qubit: str
) -> float:
    joint = {(0, 0): 0.0, (0, 1): 0.0, (1, 0): 0.0, (1, 1): 0.0}
    left_index = _qubit_index(left_qubit)
    right_index = _qubit_index(right_qubit)
    for basis_index, amplitude in state.items():
        left = _bit_at(basis_index, left_index)
        right = _bit_at(basis_index, right_index)
        joint[(left, right)] += abs(amplitude) ** 2

    left_marginal = {
        value: joint[(value, 0)] + joint[(value, 1)] for value in (0, 1)
    }
    right_marginal = {
        value: joint[(0, value)] + joint[(1, value)] for value in (0, 1)
    }
    information = 0.0
    for (left, right), probability in joint.items():
        if probability == 0.0:
            continue
        denominator = left_marginal[left] * right_marginal[right]
        information += probability * log2(probability / denominator)
    return information


def _reduced_density_matrix(
    state: dict[int, complex], keep: tuple[str, ...]
) -> dict[tuple[int, int], complex]:
    keep_indices = tuple(_qubit_index(qubit) for qubit in keep)
    traced_indices = tuple(index for index in range(len(QUBITS)) if index not in keep_indices)
    reduced: dict[tuple[int, int], complex] = {}
    entries = tuple(state.items())
    for left_basis, left_amplitude in entries:
        left_trace_bits = tuple(_bit_at(left_basis, index) for index in traced_indices)
        left_keep = _project_bits(left_basis, keep_indices)
        for right_basis, right_amplitude in entries:
            right_trace_bits = tuple(_bit_at(right_basis, index) for index in traced_indices)
            if left_trace_bits != right_trace_bits:
                continue
            right_keep = _project_bits(right_basis, keep_indices)
            key = (left_keep, right_keep)
            reduced[key] = reduced.get(key, 0j) + left_amplitude * right_amplitude.conjugate()
    return reduced


def _project_bits(basis_index: int, indices: tuple[int, ...]) -> int:
    projected = 0
    for index in indices:
        projected = (projected << 1) | _bit_at(basis_index, index)
    return projected


def _bit_at(basis_index: int, qubit_index: int) -> int:
    shift = len(QUBITS) - 1 - qubit_index
    return (basis_index >> shift) & 1


def _qubit_index(qubit: str) -> int:
    return QUBITS.index(qubit)


def _reversal_cost_below_threshold(
    accessible_support_count: int, reconstruction_threshold: int
) -> int:
    if accessible_support_count < reconstruction_threshold:
        return 0
    return accessible_support_count - reconstruction_threshold + 1


def _observer_by_name(stage: StageAnalysis, name: str) -> ObserverAnalysis:
    for observer in stage.observers:
        if observer.observer.name == name:
            return observer
    raise ValueError(f"unknown observer: {name}")


def _stage_to_dict(stage: StageAnalysis) -> dict[str, object]:
    return {
        "step": stage.step,
        "name": stage.name,
        "active_records": [asdict(record) for record in stage.active_records],
        "pointer_coherence_abs": stage.pointer_coherence_abs,
        "system_apparatus_probabilities": stage.system_apparatus_probabilities,
        "fragment_information_bits": stage.fragment_information_bits,
        "environment_r_delta_total": stage.environment_r_delta_total,
        "observers": [
            {
                "name": analysis.observer.name,
                "accessible_holders": sorted(analysis.observer.accessible_holders),
                "accessible_records": list(analysis.accessible_records),
                "reconstruction_threshold": analysis.observer.reconstruction_threshold,
                "accessible_environment_r_delta": analysis.accessible_environment_r_delta,
                "d1_profile": asdict(analysis.d1_profile)
                | {"profile_tuple": list(analysis.d1_profile.as_tuple())},
                "interpretation": analysis.interpretation,
            }
            for analysis in stage.observers
        ],
    }
